import { ArrowUpRight, BriefcaseBusiness, Check } from 'lucide-react'
import { experience } from '../../data/experience'

export function ExperienceSection() {
  return (
    <section className="mx-auto w-[min(100%-2rem,72rem)] py-20 sm:py-28" aria-labelledby="experience-heading">
      <div className="max-w-2xl"><p className="mb-4 text-xs font-bold uppercase tracking-[0.18em] text-[var(--color-accent)]">Experience</p><h2 id="experience-heading" className="m-0 text-4xl font-semibold tracking-[-0.045em] text-[var(--color-ink)] sm:text-5xl">Backend development experience.</h2><p className="mt-5 mb-0 text-base leading-7 text-[var(--color-muted)]">Professional backend development roles and the technologies used in each engagement.</p></div>
      <ol className="relative mt-12 space-y-8 border-l border-[var(--color-line)] pl-7 sm:pl-10">
        {experience.map((entry) => <li key={`${entry.organization}-${entry.startDate}`} className="relative"><span className="absolute -left-[2.45rem] top-0 grid size-9 place-items-center rounded-full border border-[var(--color-line)] bg-[var(--color-surface)] text-[var(--color-accent)] sm:-left-[3.2rem]"><BriefcaseBusiness aria-hidden="true" size={17} /></span><article className="rounded-2xl border border-[var(--color-line)] bg-[var(--color-surface)] p-5 sm:p-6"><div className="flex flex-col gap-2 border-b border-[var(--color-line)] pb-5 sm:flex-row sm:items-start sm:justify-between"><div><h3 className="m-0 text-xl font-semibold tracking-[-0.03em] text-[var(--color-ink)]">{entry.role}</h3><p className="mt-1 mb-0 text-sm font-medium text-[var(--color-accent)]">{entry.organization}{entry.websiteUrl ? <a className="ml-2 inline-flex align-middle text-[var(--color-accent)] hover:text-[var(--color-accent-strong)]" href={entry.websiteUrl} target="_blank" rel="noreferrer"><span className="sr-only">Visit {entry.organization}</span><ArrowUpRight aria-hidden="true" size={15} /></a> : null}</p></div><p className="m-0 text-sm text-[var(--color-muted)]">{entry.startDate} – {entry.endDate}</p></div><p className="mt-5 mb-0 text-sm leading-6 text-[var(--color-muted)]">{entry.summary}</p><div className="mt-6 grid gap-6 lg:grid-cols-[0.85fr_1.15fr]"><div><h4 className="m-0 text-xs font-bold uppercase tracking-[0.14em] text-[var(--color-muted)]">Key responsibility</h4><ul className="mt-3 space-y-2 p-0">{entry.responsibilities.map((responsibility) => <li key={responsibility} className="flex gap-2 text-sm leading-6 text-[var(--color-ink)]"><Check aria-hidden="true" size={16} className="mt-1 shrink-0 text-[var(--color-accent)]" />{responsibility}</li>)}</ul></div><div><h4 className="m-0 text-xs font-bold uppercase tracking-[0.14em] text-[var(--color-muted)]">Technologies</h4><ul className="mt-3 flex flex-wrap gap-1.5 p-0">{entry.highlights.map((technology) => <li key={technology} className="list-none rounded-md border border-[var(--color-line)] bg-[var(--color-surface-raised)] px-2 py-1 text-xs text-[var(--color-muted)]">{technology}</li>)}</ul></div></div></article></li>)}
      </ol>
    </section>
  )
}
